# Generated by Django 4.2.3 on 2023-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0008_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='ratings',
            name='book_id',
            field=models.IntegerField(blank=True, db_column='Book_ID', null=True),
        ),
    ]
