# Generated by Django 4.2.3 on 2023-08-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0009_remove_ratings_isbn_ratings_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
